// XPath description of elements of default functions
export const locators = {
  checkpointPullDown: "//div[@id='setting_sd_model_checkpoint']//div[contains(@class,'secondary-wrap')]",
  checkpointList: (modelName) => `//div[@id='setting_sd_model_checkpoint']//li[contains(@data-value,'${modelName}')]`,
  checkpointLoaded: "//div[@id='setting_sd_model_checkpoint']//div[contains(@class,'wrap default svelte-gjihhp hide')]",
  vaePullDown: "//div[@id='setting_sd_vae']//div[contains(@class,'secondary-wrap')]",
  vaeList: (modelName) => `//div[@id='setting_sd_vae']//li[contains(@data-value,'${modelName}')]`,
  vaeLoaded: "//div[@id='setting_sd_vae']/child::div[1]",
  clipSkip: "//div[@id='setting_CLIP_stop_at_last_layers']//input[@type='number']",
  tabs: {
    t2i: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='txt2img']",
    i2i: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='i2i2img']",
    extras: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='Extras']",
    pngInfo: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='PNG Info']",
    settings: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='Settings']",
    extensions: "//div[@id='quicksettings']/following-sibling::div[1]/child::div[1]//button[text()='Extensions']",
  },
  t2i: {
    promptTextarea: "//div[@id='txt2img_prompt']//textarea",
    negativeTextarea: "//div[@id='txt2img_neg_prompt']//textarea",
    tools: {
      clear: "//button[@id='txt2img_clear_prompt']",
      apply: "//button[@id='txt2img_style_apply']",
    },
    styles: "//div[@id='txt2img_styles']//input",
    generateBtn: "//button[@id='txt2img_generate']",
    txt2imgGallery: "//div[@id='txt2img_gallery']//button[1]",
    txt2imgGalleryThumb: "//div[@id='txt2img_gallery']//div[contains(@class,'thumbnails')]",
    sendToI2iBtn: "//div[@id='tab_txt2img']//button[@id='img2img_tab']",
    sendToInpaintBtn: "//div[@id='tab_txt2img']//button[@id='inpaint_tab']",
    sendToExtrasBtn: "//div[@id='tab_txt2img']//button[@id='extras_tab']",
    interrupt: "//button[@id='txt2img_interrupt' and contains(@style, 'display: block;')]",
    params: {
      samplerPullDown: "//div[@id='txt2img_sampling']",
      samplerList: (sampler) => `//div[@id='txt2img_sampling']//li[@data-value='${sampler}']`,
      steps: "//div[@id='txt2img_steps']//input[contains(@type,'number')]",
      width: "//div[@id='txt2img_width']//input[contains(@type, 'number')]",
      height: "//div[@id='txt2img_height']//input[contains(@type, 'number')]",
      batchCount: "//div[@id='txt2img_batch_count']//input[contains(@type, 'number')]",
      batchSize: "//div[@id='txt2img_batch_size']//input[contains(@type, 'number')]",
      cfgScale: "//div[@id='txt2img_cfg_scale']//input[contains(@type, 'number')]",
      seed: "//div[@id='txt2img_seed']//input[contains(@type, 'number')]",
    },
    hiresFix: {
      chkbox: "//div[@id='txt2img_enable_hr']//input[contains(@type, 'checkbox')]",
      upScalerDropBox: "//div[@id='txt2img_hr_upscaler']//div[contains(@class,'secondary-wrap')]",
      upScalerList: (upScaler) => `//div[@id='txt2img_hr_upscaler']//ul/li[@data-value='${upScaler}']`,
      hiresSteps: "//div[@id='txt2img_hires_steps']//input[contains(@type,'number')]",
      strength: "//div[@id='txt2img_denoising_strength']//input[contains(@type,'number')]",
      upScaleBy: "//div[@id='txt2img_hr_scale']//input[contains(@type,'number')]",
      width: "//div[@id='txt2img_hr_resize_x']//input[contains(@type,'number')]",
      height: "//div[@id='txt2img_hr_resize_y']//input[contains(@type,'number')]",
    },
  },
  i2i: {
    promptTextarea: "//div[@id='img2img_prompt']//textarea",
    negativeTextarea: "//div[@id='img2img_neg_prompt']//textarea",
    tools: {
      clear: "//button[@id='img2img_clear_prompt']",
      apply: "//button[@id='img2img_style_apply']",
    },
    styles: "//div[@id='img2img_styles']//input",
    generateBtn: "//button[@id='img2img_generate']",
    sendToI2iBtn: "//div[@id='tab_img2img']//button[@id='img2img_tab']",
    sendToInpaintBtn: "//div[@id='tab_img2img']//button[@id='inpaint_tab']",
    sendToExtrasBtn: "//div[@id='tab_img2img']//button[@id='extras_tab']",
    interrupt: "//button[@id='img2img_interrupt' and contains(@style, 'display: block;')]",
    params: {
      samplerPullDown: "//div[@id='img2img_sampling']",
      samplerList: (sampler) => `//div[@id='img2img_sampling']//li[@data-value='${sampler}']`,
      steps: "//div[@id='img2img_steps']//input[contains(@type,'number')]",
      width: "//div[@id='img2img_width']//input[contains(@type, 'number')]",
      height: "//div[@id='img2img_height']//input[contains(@type, 'number')]",
      batchCount: "//div[@id='img2img_batch_count']//input[contains(@type, 'number')]",
      batchSize: "//div[@id='img2img_batch_size']//input[contains(@type, 'number')]",
      cfgScale: "//div[@id='img2img_cfg_scale']//input[contains(@type, 'number')]",
      strength: "//div[@id='img2img_denoising_strength']//input[contains(@type, 'number')]",
      seed: "//div[@id='img2img_seed']//input[contains(@type, 'number')]",
    },
  },
  extras: {},
  pngInfo: {},
  settings: {},
  extensions: {},
};

// //Tabs
